---
ID: "ec522edf-3db6-428e-adc9-40001cc6a8c1"
Parent: "6df777e9-53d9-4ae0-9499-3d807bc4b1f2"
Template: "6df777e9-53d9-4ae0-9499-3d807bc4b1f2"
Path: /sitecore/templates/Feature/EXM/_HtmlContent/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200705T200308Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
