version: "2.4"

services:

  sql:
    image: ${REGISTRY}sitecore-xp-sxa-sqldev:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    volumes:
      - .\data\sql:C:\Data
    mem_limit: 2GB
    ports:
      - "44010:1433"

  solr:
    image: ${REGISTRY}sitecore-xp-sxa-solr:${SITECORE_VERSION}-nanoserver-${NANOSERVER_VERSION}
    volumes:
      - .\data\solr:C:\Data
    mem_limit: 1GB
    ports:
      - "44011:8983"

  xconnect:
    image: ${REGISTRY}sitecore-xp-xconnect:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -Command "& C:\\tools\\entrypoints\\xconnect\\Development.ps1"
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\xconnect:C:\inetpub\wwwroot\App_Data\logs
    mem_limit: 1GB
    links:
      - sql
      - solr
    depends_on:
      sql:
        condition: service_healthy
      solr:
        condition: service_started

  xconnect-automationengine:
    image: ${REGISTRY}sitecore-xp-xconnect-automationengine:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\xconnect-automationengine:C:\AutomationEngine\App_Data\logs
    mem_limit: 500MB
    links:
      - sql
      - xconnect
    depends_on:
      sql:
        condition: service_healthy
      xconnect:
        condition: service_started

  xconnect-indexworker:
    image: ${REGISTRY}sitecore-xp-xconnect-indexworker:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\xconnect-indexworker:C:\IndexWorker\App_Data\logs
    mem_limit: 500MB
    links:
      - sql
      - solr
    depends_on:
      sql:
        condition: service_healthy
      solr:
        condition: service_started

  xconnect-processingengine:
    image: ${REGISTRY}sitecore-xp-xconnect-processingengine:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\xconnect-processingengine:C:\ProcessingEngine\App_Data\logs
    mem_limit: 500MB
    restart: unless-stopped
    links:
      - sql
      - xconnect
    depends_on:
      sql:
        condition: service_healthy
      xconnect:
        condition: service_started

  cd:
    image: ${REGISTRY}sitecore-xp-sxa-cd:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\cd:C:\inetpub\wwwroot\App_Data\logs
      - .\deploy\website:c:\src
    ports:
      - "44002:80"
    links:
      - sql
      - solr
      - xconnect
    depends_on:
      sql:
        condition: service_healthy
      solr:
        condition: service_started
      xconnect:
        condition: service_started

  cm:
    image: ${REGISTRY}sitecore-xp-sxa-standalone:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\cm:C:\inetpub\wwwroot\App_Data\logs
      - .\deploy\website:c:\src
      - .\deploy\serialization:c:\Serialization
    ports:
      - "44001:80"
    links:
      - sql
      - solr
      - xconnect
    depends_on:
      sql:
        condition: service_healthy
      solr:
        condition: service_started
      xconnect:
        condition: service_started
