---
ID: "d5c5f889-c5f7-4aad-8ab8-52e47a4ea23e"
Parent: "07b2bc80-642c-4a57-b482-ab7a3b0013e9"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/layout/Layouts/Project/Example/MVC
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200705T190957Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
